version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iluvcoffeedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
